name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Build Frontend Image
      - name: Build frontend Docker image
        run: docker build -t frontend ./Frontend

      # Build Backend Image
      - name: Build backend Docker image
        run: docker build -t backend ./Backend